apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
      - name: my-app
        image: 730335323304.dkr.ecr.ap-south-1.amazonaws.com/weatcher_app:weather_app-v1.52
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
